In [1]:
from nsepython import *
from datetime import date
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

In [2]:
# Inflation rate is 3.85% as of 2023 April
inflation_rate = 0.0385

# 10 year bond yield is 7.229% as of 2023 April
bond_yield = 0.07229

# Risk free rate calculation
risk_free_rate = ((1 + bond_yield) /  (1 + inflation_rate)) - 1

print("Risk free rate is: ", risk_free_rate)

Risk free rate is:  0.032537313432835724

In [17]:
symbol = "HDFCBANK"
series = "EQ"
start_date = "01-01-2002"
end_date ="31-03-2016"
data=equity_history(symbol,series,start_date,end_date)

/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))

In [18]:
data

,_id,CH_SYMBOL,CH_SERIES,CH_MARKET_TYPE,CH_TRADE_HIGH_PRICE,CH_TRADE_LOW_PRICE,CH_OPENING_PRICE,CH_CLOSING_PRICE,CH_LAST_TRADED_PRICE,CH_PREVIOUS_CLS_PRICE,...,CH_ISIN,CH_TIMESTAMP,TIMESTAMP,createdAt,updatedAt,__v,SLBMH_TOT_VAL,VWAP,mTIMESTAMP,CA
0,641ebc1f4438f60007b5a3a4,HDFCBANK,EQ,N,1053.00,1041.65,1045.00,1047.50,1052.30,1049.35,...,INE040A01026,2016-03-28,2016-03-27T18:30:00.000Z,2023-03-25T09:17:19.098Z,2023-03-25T09:17:19.098Z,0,None,1048.62,28-Mar-2016,NaN
1,641ebc2931da23000791a595,HDFCBANK,EQ,N,1059.50,1044.25,1047.50,1053.80,1053.00,1047.50,...,INE040A01026,2016-03-29,2016-03-28T18:30:00.000Z,2023-03-25T09:17:29.178Z,2023-03-25T09:17:29.178Z,0,None,1054.95,29-Mar-2016,NaN
2,641ebc33a077ee000756e4ac,HDFCBANK,EQ,N,1069.90,1053.90,1058.00,1064.95,1066.30,1053.80,...,INE040A01026,2016-03-30,2016-03-29T18:30:00.000Z,2023-03-25T09:17:39.302Z,2023-03-25T09:17:39.302Z,0,None,1063.19,30-Mar-2016,NaN
3,641ebc3d4438f60007b5ab5a,HDFCBANK,EQ,N,1078.90,1065.05,1066.85,1071.15,1071.80,1064.95,...,INE040A01026,2016-03-31,2016-03-30T18:30:00.000Z,2023-03-25T09:17:49.415Z,2023-03-25T09:17:49.415Z,0,None,1072.96,31-Mar-2016,NaN
4,641ebb221f65df0007b40684,HDFCBANK,EQ,N,979.90,959.00,976.90,974.90,978.70,973.45,...,INE040A01026,2016-02-17,2016-02-16T18:30:00.000Z,2023-03-25T09:13:06.607Z,2023-03-25T09:13:06.607Z,0,None,969.44,17-Feb-2016,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3631,641f2e10713bb70007cb1d54,HDFCBANK,EQ,N,227.90,224.00,226.00,225.15,224.85,224.80,...,,2002-02-04,2002-02-03T18:30:00.000Z,2023-03-25T17:23:28.295Z,2023-03-25T17:23:28.295Z,0,None,225.25,04-Feb-2002,NaN
3632,641f2ec7adde0b0007d21a2b,HDFCBANK,EQ,N,226.95,220.00,224.00,222.70,220.00,225.15,...,,2002-02-05,2002-02-04T18:30:00.000Z,2023-03-25T17:26:31.116Z,2023-03-25T17:26:31.116Z,0,None,223.43,05-Feb-2002,NaN
3633,641f313b5510ab0007efe676,HDFCBANK,EQ,N,228.95,222.15,222.55,225.20,226.00,222.70,...,,2002-02-06,2002-02-05T18:30:00.000Z,2023-03-25T17:36:59.041Z,2023-03-25T17:36:59.041Z,0,None,224.15,06-Feb-2002,NaN
3634,641f2ec14438f60007b7b3bf,HDFCBANK,EQ,N,232.00,224.40,225.10,226.65,224.55,225.20,...,,2002-02-07,2002-02-06T18:30:00.000Z,2023-03-25T17:26:25.813Z,2023-03-25T17:26:25.813Z,0,None,228.34,07-Feb-2002,NaN
3635,641f30a33d38840007c8b629,HDFCBANK,EQ,N,228.00,220.00,227.75,225.05,225.00,226.65,...,,2002-02-08,2002-02-07T18:30:00.000Z,2023-03-25T17:34:27.396Z,2023-03-25T17:34:27.396Z,0,None,224.18,08-Feb-2002,NaN

In [19]:
sorted_data = data.sort_values(by=['CH_TIMESTAMP'], ascending=True)
sorted_data

,_id,CH_SYMBOL,CH_SERIES,CH_MARKET_TYPE,CH_TRADE_HIGH_PRICE,CH_TRADE_LOW_PRICE,CH_OPENING_PRICE,CH_CLOSING_PRICE,CH_LAST_TRADED_PRICE,CH_PREVIOUS_CLS_PRICE,...,CH_ISIN,CH_TIMESTAMP,TIMESTAMP,createdAt,updatedAt,__v,SLBMH_TOT_VAL,VWAP,mTIMESTAMP,CA
3607,641f31b44708d50007274d25,HDFCBANK,EQ,N,230.00,222.75,228.00,225.05,226.00,225.60,...,,2002-01-01,2001-12-31T18:30:00.000Z,2023-03-25T17:39:00.692Z,2023-03-25T17:39:00.692Z,0,None,225.02,01-Jan-2002,NaN
3608,641f32744438f60007b7ce4d,HDFCBANK,EQ,N,225.75,223.00,224.00,225.00,225.00,225.05,...,,2002-01-02,2002-01-01T18:30:00.000Z,2023-03-25T17:42:12.909Z,2023-03-25T17:42:12.909Z,0,None,224.53,02-Jan-2002,NaN
3609,641f3270adde0b0007d23e28,HDFCBANK,EQ,N,227.95,222.20,225.00,226.25,227.75,225.00,...,,2002-01-03,2002-01-02T18:30:00.000Z,2023-03-25T17:42:08.208Z,2023-03-25T17:42:08.208Z,0,None,224.70,03-Jan-2002,NaN
3610,641f326a341dfa0007d37446,HDFCBANK,EQ,N,228.00,223.50,225.00,223.95,223.75,226.25,...,,2002-01-04,2002-01-03T18:30:00.000Z,2023-03-25T17:42:02.801Z,2023-03-25T17:42:02.801Z,0,None,224.49,04-Jan-2002,NaN
3611,641f31364708d500072748bd,HDFCBANK,EQ,N,226.35,221.55,224.00,223.95,224.15,223.95,...,,2002-01-07,2002-01-06T18:30:00.000Z,2023-03-25T17:36:54.390Z,2023-03-25T17:36:54.390Z,0,None,223.79,07-Jan-2002,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29,641ebc1f4438f60007b5a3a4,HDFCBANK,EQ,N,1053.00,1041.65,1045.00,1047.50,1052.30,1049.35,...,INE040A01026,2016-03-28,2016-03-27T18:30:00.000Z,2023-03-25T09:17:19.098Z,2023-03-25T09:17:19.098Z,0,None,1048.62,28-Mar-2016,NaN
0,641ebc1f4438f60007b5a3a4,HDFCBANK,EQ,N,1053.00,1041.65,1045.00,1047.50,1052.30,1049.35,...,INE040A01026,2016-03-28,2016-03-27T18:30:00.000Z,2023-03-25T09:17:19.098Z,2023-03-25T09:17:19.098Z,0,None,1048.62,28-Mar-2016,NaN
1,641ebc2931da23000791a595,HDFCBANK,EQ,N,1059.50,1044.25,1047.50,1053.80,1053.00,1047.50,...,INE040A01026,2016-03-29,2016-03-28T18:30:00.000Z,2023-03-25T09:17:29.178Z,2023-03-25T09:17:29.178Z,0,None,1054.95,29-Mar-2016,NaN
2,641ebc33a077ee000756e4ac,HDFCBANK,EQ,N,1069.90,1053.90,1058.00,1064.95,1066.30,1053.80,...,INE040A01026,2016-03-30,2016-03-29T18:30:00.000Z,2023-03-25T09:17:39.302Z,2023-03-25T09:17:39.302Z,0,None,1063.19,30-Mar-2016,NaN
3,641ebc3d4438f60007b5ab5a,HDFCBANK,EQ,N,1078.90,1065.05,1066.85,1071.15,1071.80,1064.95,...,INE040A01026,2016-03-31,2016-03-30T18:30:00.000Z,2023-03-25T09:17:49.415Z,2023-03-25T09:17:49.415Z,0,None,1072.96,31-Mar-2016,NaN

In [22]:
sorted_data.to_csv(r'sorted_data.csv', index=False)

In [15]:
symbol = "HDFCBANK"
series = "EQ"
start_date = "01-04-2016"
end_date ="31-03-2017"
next_data=equity_history(symbol,series,start_date,end_date).sort_values(by=['CH_TIMESTAMP'], ascending=True)
next_data
# to csv
next_data.to_csv(r'next_data.csv', index=False)

/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:544: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,temp_date))
/Users/ayushdattajaiswal/miniforge3/envs/mlp/lib/python3.8/site-packages/nsepython/rahu.py:561: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total=total.append(equity_history_virgin(symbol,series,start_date,end_date))

In [3]:
# Import data from csv file
sorted_data = pd.read_csv('sorted_data.csv')

In [4]:
sorted_data['log_returns'] = np.log(sorted_data['CH_CLOSING_PRICE'] / sorted_data['CH_CLOSING_PRICE'].shift(1))
# export to csv
sorted_data.to_csv(r'sorted_data_log_returns.csv', index=False)

d_std = sorted_data['log_returns'].std()
annualized_volatility = d_std * 250 ** 0.5

# Spot price
spot_price = sorted_data['CH_CLOSING_PRICE'].iloc[-1]

In [23]:
x = sorted_data["CH_CLOSING_PRICE"].values
n = x.shape[0]
window = int(10*252)
# Calculating the log returns
log_returns = np.log(x[n-window:n-1]/x[n-window-1:n-2])

# Calculating the annualized volatility
annualized_volatility = np.std(log_returns) * np.sqrt(252)
spot_price = x[n-1]

In [5]:
print(annualized_volatility)
print(spot_price)

0.5263750101017307
1071.15

In [6]:
next_data = pd.read_csv('next_data.csv')
next_data

,_id,CH_SYMBOL,CH_SERIES,CH_MARKET_TYPE,CH_TRADE_HIGH_PRICE,CH_TRADE_LOW_PRICE,CH_OPENING_PRICE,CH_CLOSING_PRICE,CH_LAST_TRADED_PRICE,CH_PREVIOUS_CLS_PRICE,...,CH_ISIN,CH_TIMESTAMP,TIMESTAMP,createdAt,updatedAt,__v,SLBMH_TOT_VAL,VWAP,mTIMESTAMP,CA
0,641ebc4731da23000791ace4,HDFCBANK,EQ,N,1076.40,1056.80,1068.8,1064.45,1065.05,1071.15,...,INE040A01026,2016-04-01,2016-03-31T18:30:00.000Z,2023-03-25T09:17:59.386Z,2023-03-25T09:17:59.386Z,0,NaN,1062.89,01-Apr-2016,NaN
1,641ebc51ff5c30000705b18b,HDFCBANK,EQ,N,1072.80,1064.00,1065.2,1069.05,1068.25,1064.45,...,INE040A01026,2016-04-04,2016-04-03T18:30:00.000Z,2023-03-25T09:18:09.585Z,2023-03-25T09:18:09.585Z,0,NaN,1068.19,04-Apr-2016,NaN
2,641ebc5b6e7d520007c75fc5,HDFCBANK,EQ,N,1076.90,1055.65,1069.0,1057.45,1056.30,1069.05,...,INE040A01026,2016-04-05,2016-04-04T18:30:00.000Z,2023-03-25T09:18:19.671Z,2023-03-25T09:18:19.671Z,0,NaN,1064.16,05-Apr-2016,NaN
3,641ebc656e7d520007c7676f,HDFCBANK,EQ,N,1066.95,1056.75,1061.0,1061.50,1063.10,1057.45,...,INE040A01026,2016-04-06,2016-04-05T18:30:00.000Z,2023-03-25T09:18:29.754Z,2023-03-25T09:18:29.754Z,0,NaN,1062.92,06-Apr-2016,NaN
4,641ebc6f25e37500078751df,HDFCBANK,EQ,N,1064.75,1047.05,1064.0,1055.50,1056.00,1061.50,...,INE040A01026,2016-04-07,2016-04-06T18:30:00.000Z,2023-03-25T09:18:39.866Z,2023-03-25T09:18:39.866Z,0,NaN,1056.31,07-Apr-2016,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,5f2aa85c434c8f000824b624,HDFCBANK,EQ,N,1424.00,1404.05,1424.0,1409.85,1411.95,1424.35,...,INE040A01026,2017-03-27,2017-03-26T18:30:00.000Z,2020-08-05T12:38:52.278Z,2020-08-05T12:38:52.278Z,0,NaN,1412.28,27-Mar-2017,NaN
251,5f2aa8666880400008ed6ea5,HDFCBANK,EQ,N,1424.70,1413.10,1418.3,1420.20,1421.10,1409.85,...,INE040A01026,2017-03-28,2017-03-27T18:30:00.000Z,2020-08-05T12:39:02.554Z,2020-08-05T12:39:02.554Z,0,NaN,1421.69,28-Mar-2017,NaN
252,5f2aa870083f1b0008788cd9,HDFCBANK,EQ,N,1434.80,1420.00,1420.8,1428.60,1429.55,1420.20,...,INE040A01026,2017-03-29,2017-03-28T18:30:00.000Z,2020-08-05T12:39:12.879Z,2020-08-05T12:39:12.879Z,0,NaN,1428.63,29-Mar-2017,NaN
253,5f2aa87b434c8f000824be45,HDFCBANK,EQ,N,1479.95,1425.05,1428.0,1466.20,1460.00,1428.60,...,INE040A01026,2017-03-30,2017-03-29T18:30:00.000Z,2020-08-05T12:39:23.037Z,2020-08-05T12:39:23.037Z,0,NaN,1462.08,30-Mar-2017,NaN
254,5f2aa885fe882b0009f63112,HDFCBANK,EQ,N,1454.00,1436.55,1453.8,1442.55,1440.00,1466.20,...,INE040A01026,2017-03-31,2017-03-30T18:30:00.000Z,2020-08-05T12:39:33.281Z,2020-08-05T12:39:33.281Z,0,NaN,1442.01,31-Mar-2017,NaN

In [7]:
m=10000
T=30.0/252
# for t in range(T):
def generate_prices(spot_price, risk_free_rate, annualized_volatility, T):
    expected_price = spot_price * np.exp((risk_free_rate - 0.5 * annualized_volatility ** 2) * T + annualized_volatility * np.sqrt(T) * np.random.normal(0, 1, m))
    return expected_price
mean_price = generate_prices(spot_price, risk_free_rate, annualized_volatility, T)
print(spot_price)
print(mean_price)

1071.15
[ 970.92396466  927.8029903   794.92948054 ...  836.50697346 1067.13671471
 1116.90123854]

In [17]:
strike_price = 1090.00
# spot_price = 168.34
# annualized_volatility = 0.593305
# risk_free_rate = 0.0202
# T = 0.147945

# call_payoff = np.maximum(mean_price - strike_price, 0)
# put_payoff = np.maximum(strike_price - mean_price, 0)

# print(call_payoff)
# print(put_payoff)

In [18]:
# Calculating Payoffs
def payoff_generation(strike_price, simulation_count = 10000):
    call_payoffs = []
    put_payoffs = []
    for i in range(simulation_count):
        mean_price = generate_prices(spot_price, risk_free_rate, annualized_volatility, T)
        call_payoff = np.maximum(mean_price - strike_price, 0)
        put_payoff = np.maximum(strike_price - mean_price, 0)
        call_payoffs.append(call_payoff)
        put_payoffs.append(put_payoff)
    return call_payoffs, put_payoffs

In [19]:
# Calculating the call and put option prices
def option_price_calculation(strike_price, simulation_count = 10000):
    call_payoffs, put_payoffs = payoff_generation(strike_price, simulation_count)
    call_price = np.mean(call_payoffs) * np.exp(-risk_free_rate * T)
    put_price = np.mean(put_payoffs) * np.exp(-risk_free_rate * T)
    return call_payoffs, put_payoffs, call_price, put_price

In [20]:
# Executing the function
call_payoffs, put_payoffs, call_price, put_price = option_price_calculation(strike_price)

In [21]:
print("Call Option price is: ", call_price)
print("Put Option price is: ", put_price)

# # Plotting the call and put option prices
# plt.figure(figsize=(10, 6))
# plt.hist(call_payoffs, bins=50)
# plt.xlabel("Call Payoff")
# plt.ylabel("Frequency")
# plt.show()
# plt.figure(figsize=(10, 6))
# plt.hist(put_payoffs, bins=50)
# plt.xlabel("Put Payoff")
# plt.ylabel("Frequency")
# plt.show()

Call Option price is:  70.92208358290367
Put Option price is:  85.55898768524366

In [22]:
# Calculating Put Call Parity
def put_call_parity_calculation(call_price, put_price, spot_price, strike_price, risk_free_rate, T):
    lhs = call_price - put_price
    rhs = spot_price - strike_price * np.exp(-risk_free_rate * T)
    return round(lhs) == round(rhs)

# Executing the function
put_call_parity_calculation(call_price, put_price, spot_price, strike_price, risk_free_rate, T)

True

In [23]:
# Now lets calculate the option price using Black Scholes formula
# First we need to calculate the d1 and d2 values

# Calculating d1
def d1_calculation(spot_price, strike_price, risk_free_rate, annualized_volatility, T):
    d1 = (np.log(spot_price/strike_price) + (risk_free_rate + 0.5 * annualized_volatility**2) * T) / (annualized_volatility * np.sqrt(T))
    return d1

# Calculating d2
def d2_calculation(spot_price, strike_price, risk_free_rate, annualized_volatility, T):
    d2 = (np.log(spot_price/strike_price) + (risk_free_rate - 0.5 * annualized_volatility**2) * T) / (annualized_volatility * np.sqrt(T))
    return d2

In [24]:
# Calculating the call and put option prices using Black Scholes formula
def option_price_calculation_black_scholes(spot_price, strike_price, risk_free_rate, annualized_volatility, T):
    d1 = d1_calculation(spot_price, strike_price, risk_free_rate, annualized_volatility, T)
    d2 = d2_calculation(spot_price, strike_price, risk_free_rate, annualized_volatility, T)
    call_price = spot_price * norm.cdf(d1) - strike_price * np.exp(-risk_free_rate * T) * norm.cdf(d2)
    put_price = strike_price * np.exp(-risk_free_rate * T) * norm.cdf(-d2) - spot_price * norm.cdf(-d1)
    return call_price, put_price

In [25]:
# Executing the function
call_price_black_scholes, put_price_black_scholes = option_price_calculation_black_scholes(spot_price, strike_price, risk_free_rate, annualized_volatility, T)
print("Call Option price using Black Scholes formula is: ", call_price_black_scholes)
print("Put Option price using Black Scholes formula is: ", put_price_black_scholes)

Call Option price using Black Scholes formula is:  70.93178802612016
Put Option price using Black Scholes formula is:  85.56785084915168